workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - APP_STORE_CONNECT  # Your environment variable group
      ios_signing:
        distribution_type: development
        bundle_identifier: B46X894ZHC.Mirro.Social.App  # CORRECTED BUNDLE ID
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "B46X894ZHC.Mirro.Social.App"  # CORRECTED BUNDLE ID
      node: 18
      xcode: latest
      cocoapods: default
    
    cache:
      cache_paths:
        - $HOME/.yarn
        - node_modules
    
    scripts:
      - name: Install dependencies
        script: |
          yarn install
          
      - name: Build Next.js app
        script: |
          yarn build
          
      - name: Update Capacitor config with correct bundle ID
        script: |
          # Update the bundle ID in capacitor.config.ts before syncing
          sed -i '' "s/com.mirro2.app/B46X894ZHC.Mirro.Social.App/g" capacitor.config.ts || true
          
      - name: Capacitor sync
        script: |
          npx cap sync ios
          
      - name: Set up keychain
        script: |
          keychain initialize
          
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            "B46X894ZHC.Mirro.Social.App" \
            --type IOS_APP_DEVELOPMENT \
            --platform IOS \
            --create
          
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
          
      - name: Set up code signing
        script: |
          xcode-project use-profiles
          
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - agentverse884@gmail.com
        notify:
          success: true
          failure: true